### ISSUE TITLE
Accessibility suggestions for links in cards

### ISSUE THREAD

**Issue by MrMcFortna** [web-illinois/ilw-card#1]
Accessibility suggestions for https://github.com/web-illinois/ilw-card/README.md and https://github.com/web-illinois/ilw-card/blob/main/builder/versions/ilw-card.1.0.0-alpha.json:

- Add reminder to Accessibility Notes to include an aria-label on each button or button-style link in the card with brief content (e.g. Learn More, Contact Us)
- Update examples to include an aria-label for these types of links, e.g. in Clickable Card section, update link to the following: `<p><a href="#" class="ilw-button" aria-label="Contact Us about Student Life">Contact Us</a></p>`

**Comment by marvel-uiuc** [comment]
I see that the JSON does not include the example, but the README does mention this issue, although it should probably be a bit clearer.

Rather than using an `aria-label`, I lean towards adding a span that's visually hidden to the contents, and there's one example of that in the README:

```html
<a href="#" class="ilw-button">Learn More <span class="ilw-sr-only">About Student Life</span>
```

The reason I prefer this approach is because that guarantees it meets [WCAG Label In Name](https://www.w3.org/WAI/WCAG21/Understanding/label-in-name), since the beginning of the text is used for both. It's less likely you'll accidentally change one or the other without updating both.

I'll make the wording a bit clearer and add the example to the JSON as well.

**Comment by marvel-uiuc** [comment]
I have clarified the README, and made sure the samples include it as well.
